version: '3'

services:
  na_notes:
    image: 'priyankasaha2/keep-note-final-noteservice:latest'
    build: .
    container_name: na_notes
    ports:
      - '3001:3001'
    networks:
      - na_network
    environment:
      - MONGO_URL=mongodb://na_mongodb:27017/keep
      - USER_URL=http://localhost:3000/api/v1/auth
      - LOG_LEVEL=debug
    restart: on-failure
    depends_on:
      - na_mongodb
      - na_users
  na_users:
    image: 'priyankasaha2/keep-note-final-userservice:latest'
    build: ../userService
    container_name: na_users
    ports:
      - '3000:3000'
    networks:
      - na_network
    environment:
      - MONGO_URL=mongodb://na_mongodb:27017/keep
      #- MONGO_URL=mongodb://localhost:27017/keep
      - LOG_LEVEL=debug
    restart: on-failure
    depends_on:
      - na_mongodb
  na_mongodb:
    image: 'mongo:4.1.1-xenial'
    container_name: na_mongodb
    expose:
      - 27017
    ports:
      - '27017:27017'
    networks:
      - na_network

networks:
  na_network:
    driver: bridge
    #driver: host