version: '3'

services:
  na_apigateway:
    image: 'priyankasaha2/keep-note-final-apigateway:latest'
    build: .
    container_name: na_apigateway
    ports:
      - '8000:8000'
    networks:
      - na_networks_apigateway
    environment:
      - MONGO_URL=mongodb://na_mongodb:27017/keep
      - USER_URL=http://localhost:3000
      - NOTES_URL=http://localhost:3001
      - NOTIFICATIONS_URL=http://localhost:3003
    restart: 
      condition: on-failure
    depends_on:
      - na_mongodb
  na_mongodb:
    image: 'mongo:4.1.1-xenial'
    container_name: na_mongodb
    expose:
      - 27017
    ports:
      - '27017:27017'
    networks:
      - na_networks_apigateway

networks:
  na_networks_apigateway:
    driver: bridge
    #driver: host